services:
  postgres:
    image: postgres:16
    container_name: checklist_postgres
    restart: always
    environment:
      POSTGRES_USER: checklist
      POSTGRES_PASSWORD: checklist
      POSTGRES_DB: checklist_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
